// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz922DK54JpUWHNlnVd3-WP-jOl5NtqZk',
    appId: '1:230545955082:web:fdf6bed225b34b778782f3',
    messagingSenderId: '230545955082',
    projectId: 'safenet-og',
    authDomain: 'safenet-og.firebaseapp.com',
    storageBucket: 'safenet-og.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHc8JQFQ2Lewx3_caFkbWG93gPiY25xBM',
    appId: '1:230545955082:android:114f679fc1e18fd88782f3',
    messagingSenderId: '230545955082',
    projectId: 'safenet-og',
    storageBucket: 'safenet-og.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVPdcnxUZrfRNllfiVkR8gJ53aC30ChYw',
    appId: '1:230545955082:ios:0f4702a996e428188782f3',
    messagingSenderId: '230545955082',
    projectId: 'safenet-og',
    storageBucket: 'safenet-og.firebasestorage.app',
    iosBundleId: 'com.example.safenetai',
  );

}
